---
logging:
  level: INFO
  loggers:
    com.aheath: DEBUG

# use the simple server factory if you only want to run on a single port
server:
  type: simple
  connector:
    type: http
    port: 8443

# Database Settings
database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/plantpoppa_db
  user: postgres
  password: ${DATABASE_PASSWORD}
