FROM maven:3.8.5-openjdk-17 AS build

ARG DB_USER
ARG DB_PW
ARG DB_URL
ARG JWT_SECRET
ARG JWT_ISSUER
ARG JWT_ADMIN

ARG DB

CMD ["mkdir", "app"]
WORKDIR app/

EXPOSE 8080


ENV PLANTPOPPA_DATASOURCE_USER=$DB_USER
ENV PLANTPOPPA_DATASOURCE_PW=$DB_PW

ENV PLANTPOPPA_DATASORUCE_URL=$DB_URL
ENV SPRING_DATASOURCE_URL=$DB_URL

ENV JWT_SECRET=$JWT_SECRET
ENV JWT_ISSUER=$JWT_ISSUER
ENV JWT_ADMIN_ROLE=$JWT_ADMIN


ARG JAR_FILE=target/auth-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} app.jar
ADD application.properties application.properties
ADD application-prod.properties application-prod.properties

ENTRYPOINT ["java", "-jar", "app.jar"]